### ISSUE TITLE
consider makefile

### ISSUE THREAD

**Issue by bentheiii** [biocatchltd/yellowbox#25]
@aviramha thinks we should have a Makefile or other construction tool. We should consider this. I'm generally in favour (although we should consider an alternative to makefile (loke Scons)

**Comment by aviramha** [comment]
We need to have this + docs on how to use it - the use cases are as follows:

- auto formatting
- testing
- coverage
- ?

I looked up SCons, looks unrelated and overkill. From my experience the options are either a scripts directory, containing lint.sh, format.sh and such. My preferred option of course is a Makefile.

**Comment by bentheiii** [comment]
I'm in favor of a scripts dir
