### ISSUE TITLE
add mangement to other services

### ISSUE THREAD

**Issue by bentheiii** [biocatchltd/yellowbox#29]
the management feature in rabbit has proven useful, we should add it to other services, if that proves simple.

**Comment by bharel** [comment]
Redis already allows it with insight. Azure has a connection string which can be used for storage explorer.

What is the equivalent for Kafka, our retarded child?

**Comment by bentheiii** [comment]
There are many options that all seem equally awful, I think kafka will be left without.

Does that actually cover all of them?

**Comment by bharel** [comment]
Yup.
