### ISSUE TITLE
new service superclass to automatically build and run from a dockerfile

### ISSUE THREAD

**Issue by bentheiii** [biocatchltd/yellowbox#40]
We ourselves have seen some need of this. What I'm thinking is a user writing a dockerfile and then doing

```
freshly_built = BuiltService(docker_client, "path/to/DockerFile", **build_kwargs)
```

Maybe there's even a point to:
```
with BuiltService.run(docker_client, "path/to/DockerFile", **build_kwargs) as freshly_built:
    ...
```

**Comment by bentheiii** [comment]
If this is implemented, we could expand this idea by auto-inserting debugging tokens (for python at least), and even updating local libraries.

**Comment by bharel** [comment]
I always hesitate and wonder once again, if a `from_dockerfile()` can work. The issue is always that the passed parameters to the init can mismatch the passed container or image and we have no way of knowing.

**Comment by bentheiii** [comment]
how do you imagine `from_dockerfile` working? I'd like it to return a service. But you're right about argument confusion. In general, I'd like the arguments passed among 3 (2?) functions:

* `RunMixin.run`: Depends on whether we want `Built` to be a service, but the arguments here are (for now) limited to `remove` and `spinner`, both of which are fairly unique.
* `DockerClient.images.build`
* `DockerClient.containers.create`

Maybe we can disambiguate with classes?
```python
class BuiltService:
  def build_args()->dict:
    # if a user wants special build_args they can subclass and override
    {}
  # now the __init__ arguments are forwarded to containers.create
```

**Comment by bentheiii** [comment]
replaced by #47
