### ISSUE TITLE
Add MockServer container

### ISSUE THREAD

**Issue by aviramha** [biocatchltd/yellowbox#45]
Mockserver is a utility for easily creating HTTP mocks
I think we should add helper container for it, that will also provide adding endpoints and asserting.

**Comment by bentheiii** [comment]
The ideal implementation would also create a "mockserver client" to add expectations to the server. We need to find a suitable MockServer client library, making our own is overkill.

**Comment by aviramha** [comment]
I think now it'd be better to use https://github.com/jmartin82/mmock as it's much simpler. WDYT?

**Comment by bharel** [comment]
I just internally used SimpleHTTPServer. It worked 🤷

**Comment by aviramha** [comment]
@bharel For mocking APIs?

**Comment by bharel** [comment]
Yeah, depends on the level of detail you want. Couldn't bother even searching for a 3rd party library. Was quite simple.

**Comment by bentheiii** [comment]
@bharel is it possible to connect SimpleHTTPServer to a network? if not then it doesn't fit our needs

**Comment by aviramha** [comment]
@bentheiii He showed me his example and it was a SimpleHTTPServer running from the tester context (host), with the tested container connecting to it. I think using mmock/another mocking service is better though.

**Comment by bentheiii** [comment]
closed by #50
