### ISSUE TITLE
Implement our own `dockerclient.build`

### ISSUE THREAD

**Issue by bentheiii** [biocatchltd/yellowbox#47]
the Idea: create a function that will automatically build an image from a dockerfile

PROS:
* we could auto-insert debugging/rookout tokens into the image
* we could inject local dependant libraries into the image
* we could stream the output of the build process directly to output (like we do in current BB tests, but more fluently)

I think a good name for this function `build_dockerfile` with signature `(dockerclient, dockerfile, ..., **build_arguments) -> Image`

It can then be used:
```python
service = SingleContainerService(docker_client.create(build_dockerfile(...)))

# or even

class MySpecializedService(SingleContainerService, RunMixin):
  def __init__(docker_client, **kwargs):
    super().__init__(docker_client.create(build_dockerfile(...)), **kwargs)
```

**Comment by bharel** [comment]
We don't always want to stream the output...

**Comment by bentheiii** [comment]
It's intended to be an optional argument (stored in the `...` portion), alongside the debugging symbols and whatnot

**Comment by bharel** [comment]
Question is, how can we receive the output if we want to process it programmatically?

**Comment by bentheiii** [comment]
Not sure what you mean, a possible minimal implementation might be:

```python
def build_dockerfile(client, *build_args, out_stream=sys.stdout, **build_kwargs):
  build_log = client.api.build(*args, **build_kwargs)
  for msg_b in build_log:
      msgs = str(msg_b, 'utf-8').splitlines()
      for msg in msgs:
        d = json.loads(msg)
        s = d.get('stream')
        if s:
          print(s, file=out_stream)
        else:
          print(msg, file=out_stream)
  # extract image name from last message
  # return image

**Comment by bharel** [comment]
I want to read the build output (receive it as a string or an iterable). Know if it succeeded, failed, etc...

**Comment by bentheiii** [comment]
then we can have some processing on the messages before printing, can't we?

**Comment by bharel** [comment]
We need to expose the output, not leave it inside the function (unless we use a callback or something but it's still a bad idea).
