### ISSUE TITLE
`hostname` param of `container_connection_string` in `postresql` should be optional.

### ISSUE THREAD

**Issue by bharel** [biocatchltd/yellowbox#81]
Can use `short_id()`. Container isn't necessarily visible. Param might as well be removed.

**Comment by bentheiii** [comment]
While it's possible that making `short_id` as a default is a good idea, I don't think the parameter should be removed, the container may be aliased in other names.

**Comment by bharel** [comment]
I'm not sure if aliases remove the shortid access. If they don't, this parameter is rather useless...
